backend:
  name: git-gateway
  branch: master
  identity_url: "https://keen-colden-282a59.netlify.app/.netlify/identity"
  gateway_url: "https://keen-colden-282a59.netlify.app/.netlify/git"
  squash_merges: true

media_folder: "src/assets/images" # Media files will be stored here
public_folder: "src/assets/images/uploads" # The src attribute for uploaded media

collections:
  - name: "folders" # Used in routes, e.g. /admin/collections/recipe
    label: "folders" # Used in the UI
    folder: "src/assets/images/uploads" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}" # Filename template i.e. title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "displayPhoto", name: "displayPhoto", widget: "image"}
      - {label: "Image", name: "image", widget: "image"}